name: ğŸŒŸ Stage the App ğŸŒŸ

on:
  pull_request:
    types: 
      - labeled

jobs:
  build:
    name: ğŸ› ï¸ Build and Stage
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'stage')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

